### PR TITLE
Js bundle rolled into core/build system

### PR DESCRIPTION
**Pull request by enlore**
The idea here being that the JS package management is seamlessly integrated with the current build process, so `gulp dev` and `gulp prod` work just like they did before, except you'll end up with some `skeleton.*.js` files in the places you'd expect them.

99% sure you'll have to `npm install -g ender` before it'll work.  I'm looking into just using Ender's api to do what needs to be done without asking the user to install another global cli too, but they'll have to install Gulp anyway, so maybe no big deal.

The goal is to provide Bone writers with a consistent Skeleton Core that they can expect to work with, sort of like an API (certainly in line with the idea of a contract).  People writing Bones will know to expect the grid system, the typographical choices, the various default styles, etc. Now they can expect some basic jQuery feelings and smells, too.  

See [The Jeesh](https://github.com/ender-js/jeesh) for a lowdown of what comes with it, but in brief: 

* a domready detector/handler
* a selector engine
* a dom manipulation utiltiy
* and an event system

All of which are wrapped up to look and feel like jQuery (so you can just `$("#button-or-whateve").on("click", function (ev) { $alarmWidget.toggleClass("things-on-fire")` or whatever you're used to) while being much lighter and, more interestingly, much more in line with this philosophy of "small, simple, modular" that we're going for.

### CODE REVIEW

**Comment by gld1982ltd** [comment]
Maybe this should be moved to the bone template?

**Comment by enlore** [comment]
Negative.  Then every bone would include redundant JS.  Each bone will need to include a `bone.js` file containing the specific JS that it needs, but in order to preempt everybody and their mother from including jQuery as a dependency for their bone, my proposal is to include (not jQuery but instead) the Jeesh.  This will provide people with the basic set of front end JS functionality that (I'm unscientifically arguing) most front end devs know how to use.

**Comment by gld1982ltd** [comment]
I didn't see that it would cause redundant code. But it would, wouldn't it. Then every bone would have the jeesh, which is absolutely not necessary. I don't mean to frustrate you @enlore, but there is not much documentation on ender that I've found. It seems like there was at one time (based on the videos), but that has changed. 

Correct me if I'm wrong...
Since ender is a dependency/package manager/compiler/bundler/all around great tool, wouldn't the bone dev be able to use jquery, since ender has builtin checks and fixes for $ ?  So it would bundle jquery if the bone builder does `ender add jquery`

**Comment by gld1982ltd** [comment]
What I'm really concerned with is having a dependency on anything at all. Dev dependencies are one thing, but to have skeleton framework to depend on something in production kinda takes away from the whole minimal idea. Could we implement the ender as a bone itself? Make it 100% optional?

**Comment by enlore** [comment]
Oh, you aren't frustrating me in the least.  Please don't feel like you are.  If I get all 'noyed, I'll let you know and go take a beer break or something.  It's all good.

And ender is totally not documented very well for what it is.  I had similiar "wat?" issues when I first came across it.  

jQuery isn't available for ender to add to a build.  Instead, ender is a tool + a collection of packages that allow you to mix and match the sub components of jQuery roll your own.

Check out the [package list](https://github.com/ender-js/Ender/wiki/Ender-package-list) for ender and you can get a feel for what kind of functionality you can roll in, none of which is mandatory except a selector engine.

**Comment by benhinchley** [comment]
I feel like what ender is doing we could do ourselves with something like browserify, and creating a custom dist builder so that people can build a version that suits their needs, but I feel that if we go down this road, we are going to be building something quite complex and detracting from the minimal/no js idea of Skeleton

**Comment by enlore** [comment]
I feel that.  Including ender gives me a great deal of pause for that very reason.  I really don't want to trip on down the bloat road.

**Comment by enlore** [comment]
The microlib/modular JS ethos that underlies ender is appealing, but getting it to where people can fluently and easily roll the ender listed JS libs into and out of their projects is...

...sketchy, in terms of the potential for complexity introduced to Skeleton.

Still though, for doing anything more complicated than toy-level Bones, people will need JS.

**Comment by benhinchley** [comment]
Yeah I think this is defiantly something we should play around with, just not sure what the best solution is currently. Especially with the core not being as finalised/polished as it probably should be.

**Comment by enlore** [comment]
Cool.  How do you guys feel about just merging this into an `experimental-js` branch?  We can experiment on that and go from there.

**Comment by gld1982ltd** [comment]
experimental-js branch created

**Pull request closed without merging**
