### PR TITLE
Simplifying build system

### PR DESCRIPTION
**Pull request by gld1982ltd**
I'll fix up the documentation as soon as I get a chance.

### CODE REVIEW

**Comment by enlore** [comment]
This looks cool. Why the move away from Gulp?

**Comment by gld1982ltd** [comment]
I felt that it was overkill. We don't really need all those dependencies I'm not going to merge this in, yet. First I wanted to discuss if we need a live reload server or not. If so I would rather write up a minimal one that serves our purpose.

I'm really into keeping this project as minimal as possible in dependencies. I personally use Brackets to develop with, so a live server is not necessary for me. A watcher would be nice, though.

What if we put this in a 2.0 milestone until there is a little more feedback on it?

**Comment by enlore** [comment]
On the one hand, simple and easy are good. Lower barrier to entry for other devs to contribute.

On the other hand, downloading npm modules is simple and easy. I enjoy projects where the dev setup is `npm install` and `dev command` and I'm up and running. Especially if all the tedious crap is automated, like css processing and minification. Lower barrier to entry for other devs to contribute.

So as far as that goes, I vote yes on a server, and a watcher to automate css processing. Livereload is an easy enough to roll in as an option, though the watching and serving are more important. Plenty of people don't use editors with web servers built in, and rerunning build commands every 15 seconds to see changes sucks.

 I'm definitely not going to be writing any of those anytime soon, though, as there are good enough options already out there. Connect has good options for a server and a livereload middleware.  Chokidar is the watcher that I'm aware of, and it seems nice.

I also vote yes on tabling this until we get a proper presence set up for the framework and gain some traction.  No point in doing too much preemptive work.

:+1:

**Comment by gld1982ltd** [comment]
I have already written up the server. I'm using ecstatic with socket.io and stock node http and fs. I have some code on a watcher that is based on fs.watch. I just have the code in another repo. I was prepping to build the server with just node http and fs, but while doing so I had an idea that stopped me in my tracks.. So, after some more work and some more feedback I will push the whole codebase to a 2.0-dev branch to be reviewed.

**Comment by enlore** [comment]
Sounds good to me

**Comment by enlore** [comment]
Oh hey, looking at this again, the only thing I'd recommend changing is the use of the name bones.  We're focusing on Bones being third party components (perhaps adapted from other things to work well with Skeleton), so naming the dir for the core CSS chunks `bones` may cause confusion.

**Comment by gld1982ltd** [comment]
True. I'll rename it to core and we can then be able to add bones as a seperate folder beside core. I'll add the ability to build bones with the core. That way all one has to do is drop a bone in and say npm run build.. if the watcher/server is running the watcher will automatically rebuild with any bones as they are dropped in.. no command necessary.

**Pull request closed without merging**
